In [ ]:
print("hello")

In [3]:
import numpy as np

print("numpy version:", np.__version__) ; 


numpy version: 2.5.2


# DataTypes of Numpy


In [28]:
# 1- one-dimensional array
a1 = np.array([1, 2, 3, 4, 5,16,7,10,12])  

print(a1.shape) 
print(a1.ndim)
print(a1.size)
print(a1.dtype) 
print(type(a1))
print(np.__version__);




(9,)
1
9
int64
<class 'numpy.ndarray'>
2.5.2


In [6]:
#2- two-dimensional array
a2 = np.array([
            [1, 2, 3], 
            [4, 5, 6],
            [7, 8, 9],
            [11,23,14],
            ]
              )

In [ ]:
# 3 Dimensional array 
a3 = np.array([
            [  
                [1, 2, 3],
                [4, 5, 6]
            ],
            
            [
                [7, 8, 9],
                [10, 11, 12],
            ],
            
            [
                [13, 14, 15],
                [16, 17, 18],
            ]
            
        ])

print(a3.shape,a3.dtype)
print(a3.ndim,type(a3))
print(a3.size) 
print(a3.dtype) ; 

(3, 2, 3) int64
3 <class 'numpy.ndarray'>
18
<class 'numpy.ndarray'>


In [42]:
simple_array = np.array([1, 2, 3]) ; 
print(simple_array); 
print(simple_array.dtype);
print(simple_array.shape);
print(type(simple_array));

[1 2 3]
int64
(3,)
<class 'numpy.ndarray'>


In [53]:
ones = np.ones((2,3, 4)) ;
print(ones.astype(int));

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [4]:
zeros = np.zeros((5,3,3)) ;
print(zeros.astype(int));

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
range_array = np.arange(0,10,2);
print(range_array);


[0 2 4 6 8]


In [64]:
random_array = np.random.randint(0, 10, size=(3, 4));
print(random_array);

[[7 5 1 6]
 [5 0 6 0]
 [7 0 9 6]]


In [ ]:
np.random.random((5,3)); #random float numbers between 0 and 1
